name: CI

on: [ push, pull_request ]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Install Quasar CLI
                run: |
                    yarn global add @quasar/cli
                    echo "$(yarn global bin)" >> $GITHUB_PATH

            -   name: Install dependencies
                run: yarn install

            -   name: Build the project
                run: quasar build

            -   uses: actions/upload-artifact@v2
                if: startsWith(github.ref, 'refs/tags/')
                with:
                    name: numberninecms-admin
                    path: dist/spa

    release:
        if: startsWith(github.ref, 'refs/tags/')
        needs: [ build ]
        name: Release
        runs-on: ubuntu-latest
        steps:
            -   name: Download artifact
                uses: actions/download-artifact@v2
                with:
                    name: numberninecms-admin

            -   name: Retrieve release version
                id: vars
                run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

            -   name: Create release zip file
                run: zip -rq9 numberninecms-admin-${{ steps.vars.outputs.tag }}.zip ./*

            -   name: Create Draft Release
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ github.ref }}
                    release_name: ${{ steps.vars.outputs.tag }}
                    draft: true
                    prerelease: false

            -   uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    ARTIFACT: numberninecms-admin-${{ steps.vars.outputs.tag }}.zip
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: ./$ARTIFACT
                    asset_name: $ARTIFACT
                    asset_content_type: application/zip

            -   uses: eregon/publish-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    release_id: ${{ steps.create_release.outputs.id }}
